from console_functions.enter_password_to_vault import enter_password_to_vault
from console_functions.get_pass_from_vault import get_pass_from_vault
from console_functions.make_password import make_password

#make_password()
#enter_password_to_vault()
get_pass_from_vault()
